/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();
  static const _kFontFam = 'MyFlutterApp';
  static const IconData editIcon = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData texturesIcon = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData videoIcon = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData presetsIcon = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData colourIcon = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData temperatureIcon =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData saturationIcon =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData shadowsIcon = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData contrastIcon = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData lightIcon = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lockIcon = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData instagrammIcon =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData framesIcon = IconData(0xe810, fontFamily: _kFontFam);
}
